apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sc-gold-pvc-retain
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: sc-gold-retain
