apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snap-sc-gold-pvc-mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: sc-gold-snap-mongo
