INVENTORY:
  DEFAULT:
#Mandatory Parameters-----------------------------------------------------------------------------------

    # Specify the port to be used by HPE 3PAR plugin etcd cluster
    host_etcd_port_number: 23790
    # Plugin Driver - iSCSI
    hpedockerplugin_driver: hpedockerplugin.hpe.hpe_3par_iscsi.HPE3PARISCSIDriver
    hpe3par_ip: 10.90.97.1
    hpe3par_username: 3paradm
    hpe3par_password: 3pardata
    hpe3par_port: 8080
    hpe3par_cpg: NL_r6

    # Plugin version - Required only in DEFAULT backend
    volume_plugin: hpestorage/legacyvolumeplugin:3.3
    # Dory installer version - Required for Openshift/Kubernetes setup
    # Supported versions are dory_installer_v31, dory_installer_v32
    dory_installer_version: dory_installer_v32

#Optional Parameters------------------------------------------------------------------------------------

    logging: DEBUG
    hpe3par_snapcpg: NL_r6    

    # Uncomment to encrypt passwords in hpe.conf using defined passphrase
    #encryptor_key: < encrypt_key1 >

    #ssh_hosts_key_file: '/root/.ssh/known_hosts'
    #hpe3par_debug: True
    #suppress_requests_ssl_warning: True
    #hpe3par_iscsi_chap_enabled: True
    #use_multipath: False
    #enforce_multipath: False
    #vlan_tag: True