apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clone-sc-gold-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: sc-gold-clone
