apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sc-gold-pvc
  annotations:
    hpe.com/provisioning: 'thin'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: sc-gold
