apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: schedule-sc-gold-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: sc-snapshot
