---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sc-snapshot
provisioner: hpe.com/hpe
parameters:
  virtualCopyOf: "sc-gold-2a82c9e5-6213-11e9-8d53-0050569bb07c"
  scheduleFrequency: "10 2 * * *"
  scheduleName: "dailyOnceSchedule"
  snapshotPrefix: "pqr"
  expHrs: "5"
  retHrs: "3"
