- hosts: localhost
  tasks:
  - name: Load Storage System Vars
    include_vars: 'properties/remote_copy_properties.yml'

  - name: Create volume on source
    hpe3par_volume:
      storage_system_ip: "{{ storage_system_ip_source }}"
      storage_system_username: "{{ storage_system_username_source }}"
      storage_system_password: "{{ storage_system_password_source }}"
      state: present
      volume_name: "{{ item }}"
      size: 10
      size_unit: GiB
      cpg: SSD_r6
      snap_cpg: SSD_r6
    with_items: "{{ ['demo_volume_1', 'demo_volume_2'] }}"


  - name: Create volume on target
    hpe3par_volume:
      storage_system_ip: "{{ storage_system_ip_target }}"
      storage_system_username: "{{ storage_system_username_target }}"
      storage_system_password: "{{ storage_system_password_target }}"
      state: present
      volume_name: "{{ item }}"
      size: 10
      size_unit: GiB
      cpg: SSD_r6
      snap_cpg: SSD_r6
    with_items: "{{ ['demo_volume_1', 'demo_volume_2'] }}"

  - name: Create Remote Copy Group demo_rcg
    hpe3par_remote_copy:
      storage_system_ip: "{{ storage_system_ip_source }}"
      storage_system_username: "{{ storage_system_username_source }}"
      storage_system_password: "{{ storage_system_password_source }}"
      state: present
      remote_copy_group_name: demo_rcg
      remote_copy_targets:
      - target_name: "{{ storage_system_name_target }}"
        target_mode: sync

  - name: Add volume to remote copy group
    hpe3par_remote_copy:
      storage_system_ip: "{{ storage_system_ip_source }}"
      storage_system_username: "{{ storage_system_username_source }}"
      storage_system_password: "{{ storage_system_password_source }}"
      state: add_volume
      remote_copy_group_name: demo_rcg
      volume_name: "{{ item }}"
      admit_volume_targets:
      - target_name: "{{ storage_system_name_target }}"
        sec_volume_name: "{{ item }}"
    with_items: "{{ ['demo_volume_1', 'demo_volume_2'] }}"

  - name: remote copy group status
    hpe3par_remote_copy:
      storage_system_ip: "{{ storage_system_ip_source }}"
      storage_system_username: "{{ storage_system_username_source }}"
      storage_system_password: "{{ storage_system_password_source }}"
      state: remote_copy_status
      remote_copy_group_name: demo_rcg
    register: result

  - debug:
      msg: "{{ result.output.remote_copy_sync_status}}"

  - name: Start remote copy
    hpe3par_remote_copy:
      storage_system_ip: "{{ storage_system_ip_source }}"
      storage_system_username: "{{ storage_system_username_source }}"
      storage_system_password: "{{ storage_system_password_source }}"
      remote_copy_group_name: demo_rcg
      state: start
