---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-replication-nginx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: sc-replicated-vol

